[package]
name = "financial-importer"
version = "0.1.0"
authors = ["Travis B. Hartwell <nafai@travishartwell.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
serde = { version = "1.0.55", features = ["derive"] }
chrono = { version = "0.4.19", features = ["serde"] }
regex = "1"
toml = "0.5.8"
color-eyre = "0.5"
eyre = "0.6.5"
lazy_static = "1.4.0"
format_num = "0.1.0"