[package]
name = "financial-importer"
version = "0.1.0"
authors = ["Travis B. Hartwell <nafai@travishartwell.net>"]
edition = "2018"

[lib]
name = "financial_importer"
path = "src/lib.rs"

[[bin]]
name = "financial-importer"
path = "src/bin/main.rs"

[dependencies]
color-eyre = "0.5"
structopt = "0.3"
serde = { version = "1.0.55", features = ["derive"] }
toml = "0.5.8"
lazy_static = "1.4.0"
regex = "1"
platform-dirs = "0.3.0"
