[package]
name = "financial-importer"
version = "0.1.0"
authors = ["Travis B. Hartwell <nafai@travishartwell.net>"]
edition = "2018"

[lib]
name = "financial_importer"
path = "src/lib.rs"

[[bin]]
name = "financial-importer"
path = "src/bin/main.rs"

[dependencies]
color-eyre = "0.5"
structopt = "0.3"