#!/usr/bin/env python3

from csv import DictReader, DictWriter
from dataclasses import dataclass
import datetime
from decimal import Decimal
from functools import partial
from pathlib import Path
import sys
from typing import Any, Protocol, TypedDict

DATE_COLUMN = "date"
DESCRIPTION_COLUMN = "description"
AMOUNT_COLUMN = "amount"


@dataclass(order=True, frozen=True)
class TransactionLine:
    date: datetime.date
    description: str
    amount: Decimal

    def csv_dict(self) -> dict[str, str]:
        return {
            DATE_COLUMN: str(self.date),
            DESCRIPTION_COLUMN: self.description,
            AMOUNT_COLUMN: str(self.amount.quantize(Decimal("1.00"))),
        }


type RawRow = dict[str, str]
type Row = dict[str, Any]


def month_day_four_year_with_slashes_to_date(date_column: str, row: Row) -> Row:
    month, day, year = row[date_column].split("/")
    row[date_column] = datetime.date(int(year), int(month), int(day))
    return row


def month_day_two_year_with_slashes_to_date(date_column: str, row: Row) -> Row:
    month, day, year = row[date_column].split("/")
    year = f"20{year}"
    row[date_column] = datetime.date(int(year), int(month), int(day))
    return row


def negate_amount_string_to_decimal(amount_column: str, row: Row) -> Row:
    amount_str = row[amount_column]
    amount = Decimal(amount_str)
    row[amount_column] = -amount
    return row


def negate_credit_amount_string_to_decimal(
    amount_column: str, type_column: str, row: Row
) -> Row:
    amount_str = row[amount_column]
    amount = Decimal(amount_str)

    if row[type_column] == "Credit":
        row[amount_column] = -amount
    else:
        row[amount_column] = amount

    return row


# Capital One Constants
CAPITAL_ONE_TRANSACTION_DATE_COLUMN = "Transaction Date"
CAPITAL_ONE_TRANSACTION_DESCRIPTION_COLUMN = "Transaction Description"
CAPITAL_ONE_TRANSACTION_AMOUNT_COLUMN = "Transaction Amount"
CAPITAL_ONE_TRANSACTION_TYPE_COLUMN = "Transaction Type"

# Chase Visa Constants
CHASE_VISA_TRANSACTION_DATE_COLUMN = "Transaction Date"
CHASE_VISA_DESCRIPTION_COLUMN = "Description"
CHASE_VISA_AMOUNT_COLUMN = "Amount"


ROW_TRANSFORMERS = "row_transformers"
COLUMNS = "columns"


class Transformer(Protocol):
    def __call__(self, row: Row) -> Row: ...


class ColumnMapping(TypedDict):
    date: str
    description: str
    amount: str


class FileType(TypedDict):
    row_transformers: list[Transformer]
    columns: ColumnMapping


FILE_TYPES: dict[str, FileType] = {
    "capital-one": {
        ROW_TRANSFORMERS: [
            partial(
                month_day_two_year_with_slashes_to_date,
                CAPITAL_ONE_TRANSACTION_DATE_COLUMN,
            ),
            partial(
                negate_credit_amount_string_to_decimal,
                CAPITAL_ONE_TRANSACTION_AMOUNT_COLUMN,
                CAPITAL_ONE_TRANSACTION_TYPE_COLUMN,
            ),
        ],
        COLUMNS: {
            DATE_COLUMN: CAPITAL_ONE_TRANSACTION_DATE_COLUMN,
            DESCRIPTION_COLUMN: CAPITAL_ONE_TRANSACTION_DESCRIPTION_COLUMN,
            AMOUNT_COLUMN: CAPITAL_ONE_TRANSACTION_AMOUNT_COLUMN,
        },
    },
    "chase-visa": {
        ROW_TRANSFORMERS: [
            partial(
                month_day_four_year_with_slashes_to_date,
                CHASE_VISA_TRANSACTION_DATE_COLUMN,
            ),
            partial(negate_amount_string_to_decimal, CHASE_VISA_AMOUNT_COLUMN),
        ],
        COLUMNS: {
            DATE_COLUMN: CHASE_VISA_TRANSACTION_DATE_COLUMN,
            DESCRIPTION_COLUMN: CHASE_VISA_DESCRIPTION_COLUMN,
            AMOUNT_COLUMN: CHASE_VISA_AMOUNT_COLUMN,
        },
    },
}


def load_input_file(input_file: Path) -> list[RawRow]:
    with input_file.open() as f:
        reader = DictReader(f)
        return list(reader)


def transform_rows(
    transformers: list[Transformer],
    rows: list[Row],
) -> list[Row]:
    for row in rows:
        for transformer in transformers:
            row = transformer(row)
    return rows


def row_to_transaction_line(column_map: ColumnMapping, row: Row) -> TransactionLine:
    transaction_date = row[column_map[DATE_COLUMN]]
    description = row[column_map[DESCRIPTION_COLUMN]]
    amount = row[column_map[AMOUNT_COLUMN]]
    return TransactionLine(transaction_date, description, amount)


def transformed_rows_to_transaction_lines(
    column_map: ColumnMapping, rows: list[Row]
) -> list[TransactionLine]:
    line_creator = partial(row_to_transaction_line, column_map)
    transaction_lines = [line_creator(row) for row in rows]
    return sorted(transaction_lines)


def write_transaction_lines(
    transaction_lines: list[TransactionLine], output_file: Path
) -> None:
    with output_file.open("w") as f:
        writer = DictWriter(
            f, fieldnames=[DATE_COLUMN, DESCRIPTION_COLUMN, AMOUNT_COLUMN]
        )

        writer.writeheader()
        for line in transaction_lines:
            writer.writerow(line.csv_dict())


def main(file_type: str, input_file_name: str, output_file_name: str) -> bool:
    if not file_type in FILE_TYPES:
        print(f"File type '{file_type}' is not supported.", file=sys.stderr)
        return False

    transformation: FileType = FILE_TYPES[file_type]

    input_file = Path(input_file_name)
    output_file = Path(output_file_name)

    if not input_file.exists():
        print(f"File '{input_file}' does not exist.", file=sys.stderr)
        return False

    source_rows = load_input_file(input_file)
    transformed_rows = transform_rows(transformation[ROW_TRANSFORMERS], source_rows)
    transaction_lines = transformed_rows_to_transaction_lines(
        transformation[COLUMNS], transformed_rows
    )
    write_transaction_lines(transaction_lines, output_file)
    return True


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(
            f"Usage: {sys.argv[0]} <file-type> <input-file> <output-file>",
            file=sys.stderr,
        )
        sys.exit(1)

    result = main(sys.argv[1], sys.argv[2], sys.argv[3])

    if not result:
        sys.exit(1)
